### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by flavienbwk** [ragibson/Steganography#3]
Hello,

On running `stegolsb` after installing it with `pip` (or git clone), I get this error : 

```
Traceback (most recent call last):
  File "/usr/local/bin/stegolsb", line 11, in <module>
    load_entry_point('stego-lsb==1.0', 'console_scripts', 'stegolsb')()
  File "/home/majordome/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/majordome/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/majordome/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/majordome/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/stego_lsb-1.0-py2.7.egg/stego_lsb/cli.py", line 20, in <module>
    from stego_lsb import LSBSteg, StegDetect, WavSteg, bit_manipulation
  File "/usr/local/lib/python2.7/dist-packages/stego_lsb-1.0-py2.7.egg/stego_lsb/LSBSteg.py", line 88
    log.debug(f"Files read".ljust(30) + f" in {time() - start:.2f}s")
                          ^
SyntaxError: invalid syntax
```

Is it normal ?

**Comment by ragibson** [comment]
Yes, stegolsb requires Python 3 -- it will not run with Python 2.

The error message is indicating that the format strings aren't a language construct in Python 2.7.

**Comment by flavienbwk** [comment]
Please update your README.md for the installation command.
Should be : `python3 setup.py install`.

**Comment by ragibson** [comment]
I had forgotten that some people might still be using Python 2 since it's being deprecated in a few months.

I have updated the README and setup.py to more explicitly suggest and enforce using Python 3 (see 63d9e018cdaea80cb1f5a1041bca69a834a06118).
