### ISSUE TITLE
ValueError: buffer is smaller than requested size

### ISSUE THREAD

**Issue by aflamant** [ragibson/Steganography#4]
Hi,
I'm running into an error when running `stegolsb steglsb -r -i lsb_RGB.png -o output.zip`, here's the error output :
 
```
Files read                     in 0.95s
Traceback (most recent call last):
  File "/usr/local/bin/stegolsb", line 11, in <module>
    load_entry_point('stego-lsb==1.1', 'console_scripts', 'stegolsb')()
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Click-7.0-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stego_lsb-1.1-py3.6.egg/stego_lsb/cli.py", line 93, in steglsb
    LSBSteg.recover_data(input_fp, output_fp, lsb_count)
  File "/usr/local/lib/python3.6/dist-packages/stego_lsb-1.1-py3.6.egg/stego_lsb/LSBSteg.py", line 154, in recover_data
    data = recover_message_from_image(steg_image, num_lsb)
  File "/usr/local/lib/python3.6/dist-packages/stego_lsb-1.1-py3.6.egg/stego_lsb/LSBSteg.py", line 145, in recover_message_from_image
    color_data[tag_bit_height:], 8 * bytes_to_recover, num_lsb
  File "/usr/local/lib/python3.6/dist-packages/stego_lsb-1.1-py3.6.egg/stego_lsb/bit_manipulation.py", line 112, in lsb_deinterleave_list
    deinterleaved = lsb_deinterleave_bytes(carrier_bytes, num_bits, num_lsb)
  File "/usr/local/lib/python3.6/dist-packages/stego_lsb-1.1-py3.6.egg/stego_lsb/bit_manipulation.py", line 84, in lsb_deinterleave_bytes
    np.frombuffer(carrier, dtype=carrier_dtype, count=plen).view(np.uint8)
ValueError: buffer is smaller than requested size
```

Do you know what causes this or what I'm doing wrong?

**Comment by ragibson** [comment]
Can you give me the command you used to generate `lsb_RBG.png` and its output?

**Comment by ragibson** [comment]
Also, what does the LSBSteg analysis output with your input image and input file?

In particular, what was the image resolution, input filesize, and number of LSBs that you used to generate `lsb_RGB.png`?

**Comment by ragibson** [comment]
I can't replicate this issue -- I think it could occur if the file-size tag in the steganographed image is larger than what the image can actually hold. However, if this is the case, it shouldn't have been possible to generate the image in the first place.

I will try to improve the error messages in the future.

Closing for now as unreproducible.

**Comment by ragibson** [comment]
I have tweaked this error message. Instead of "buffer is smaller than requested size", it should now print something similar to
```
This image appears to be corrupted.
It claims to hold 5000 B, but can only hold 4000 B with 2 LSBs
```
